# Generated by Django 5.1.2 on 2024-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=100)),
                ('nu_telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('ds_email', models.CharField(blank=True, max_length=100, null=True)),
                ('ds_endereco', models.TextField(blank=True, null=True)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'fornecedores',
            },
        ),
    ]
