# Generated by Django 5.1.2 on 2024-10-17 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendasmodel',
            name='bo_pago',
            field=models.BooleanField(default=False),
        ),
    ]
