# Generated by Django 5.1.2 on 2024-10-17 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_vendasmodel_bo_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendasmodel',
            old_name='bo_pago',
            new_name='bo_finalizado',
        ),
    ]
