# Generated by Django 5.1.2 on 2024-10-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_rename_bo_pago_vendasmodel_bo_finalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendasmodel',
            name='dt_venda',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
