# Generated by Django 5.1.2 on 2024-10-18 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_alter_vendasmodel_dt_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaservicomodel',
            name='nu_subtotal',
        ),
    ]
