# Generated by Django 5.1.2 on 2024-10-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='nu_telefone',
            field=models.CharField(max_length=11),
        ),
    ]
