# Generated by Django 5.1.2 on 2024-10-16 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientemodel_nu_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='ds_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
