# Generated by Django 5.1.2 on 2024-10-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientemodel_ds_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemodel',
            name='ds_endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientemodel',
            name='nu_telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
