# Generated by Django 5.1.2 on 2024-10-16 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoCategoriaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=50)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'produto_categorias',
            },
        ),
        migrations.CreateModel(
            name='ProdutoTipoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=50)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'produto_tipos',
            },
        ),
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ds_nome', models.CharField(max_length=100)),
                ('nu_valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nu_quantidade_estoque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True)),
                ('dt_alteracao', models.DateTimeField(auto_now=True, null=True)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtocategoriamodel')),
                ('fk_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produtotipomodel')),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
