# Generated by Django 5.1.2 on 2024-12-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produtomodel_nu_quantidade_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtomodel',
            name='fk_tipo',
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='ds_tipo',
            field=models.CharField(choices=[('GRANEL', 'Granel'), ('CONVENCIONAL', 'Convencional')], default='Convencional', max_length=12),
        ),
        migrations.DeleteModel(
            name='ProdutoTipoModel',
        ),
    ]
